services:

  dg-frontend:
    image: becongmbh/datagerry_frontend:latest
    container_name: dg-frontend
    ports:
      - 80:80
      - 443:443
    depends_on:
      - dg-backend
    volumes:
# comment for ssl
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
# uncomment for ssl
#      - ./conf/nginx-ssl.conf:/etc/nginx/conf.d/default.conf
#      - ./conf/ssl/certs/:/etc/ssl/certs/
#      - ./conf/ssl/private/:/etc/ssl/private/
    restart: unless-stopped

  dg-backend:
    image: becongmbh/datagerry_backend:latest
    container_name: dg-backend
    depends_on:
      - mongodb
    ports:
      - 4000:4000
    volumes:
      - ./conf/cmdb.conf:/etc/datagerry/cmdb.conf
# uncomment for ssl
#      - ./conf/ssl/certs/:/etc/ssl/certs/
#      - ./conf/ssl/private/:/etc/ssl/private/

    environment:
      DATAGERRY_Database_host: "dg-mongodb"
    restart: unless-stopped

  mongodb:
    image: mongo:6.0.25
    container_name: dg-mongodb
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb

volumes:
  mongodb-data:
  mongodb-config:
